<!DOCTYPE html>
<html lang="ko">
<head>
    <title>try catch 구문사용</title>
</head>
<body>
    <script>
        function test(data){
        try{
            throw new Error('난 너무 잘난듯');
            console.log(data+' 입니다.');
        }
        catch(e){  // 에러를 잡는 역할 (e)는 try의 에러의 내용
            console.log('catch 에서 받은 에러:' +e);
            return // finally 내용을 제외하고 무조건 종료
        }
        finally{    // 무조건 실행됨
            console.log('함수 실행을 마칩니다')
        }
    }
    test('안녕')
    </script>
</body>
</html>